# Generated by Django 4.1.7 on 2023-02-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='portfolio/images/certificates/')),
                ('file', models.FileField(upload_to='portfolio/files/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationAboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_nick', models.CharField(max_length=50)),
                ('my_photo', models.ImageField(upload_to='portfolio/info/')),
                ('description_main', models.TextField()),
                ('description_second', models.TextField(blank=True)),
                ('my_resume', models.FileField(upload_to='portfolio/info/')),
                ('my_phone_number', models.CharField(max_length=20)),
                ('link_telegram', models.URLField(blank=True)),
                ('link_instagram', models.URLField(blank=True)),
                ('link_github', models.URLField(blank=True)),
                ('link_vk', models.URLField(blank=True)),
                ('link_watsapp', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('preview', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/images/portfolio/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
